<li>
								<a target="_blank" href="http://www.zhubao.com/biyu/">碧玉</a>
								<ol>
          						
									<li><a target="_blank" href="http://www.zhubao.com/biyu/baijialv/">白加绿</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/biyu/bocailv/">菠菜绿</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/biyu/fenqing/">粉青</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/biyu/yadanqing/">鸭蛋青</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/biyu/yanglv/">阳绿</a></li>
            					
								</ol>
							</li><li>
								<a target="_blank" href="http://www.zhubao.com/feicui/">翡翠</a>
								<ol>
          						
									<li><a target="_blank" href="http://www.zhubao.com/feicui/hongfei/">红翡</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/huangfei/">黄翡</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/ziluolan/">紫罗兰</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/tielongshengfeicui/">铁龙生翡翠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/mocui/">墨翠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/youqingzhong/">油青种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/youqingzhong/">油青种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/lanshui/">蓝水</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/wujizhongfeicui/">乌鸡种翡翠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/bingzhong/">冰种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/douzhong/">豆种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/furongzhong/">芙蓉种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/bolizhong/">玻璃种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/shuizhong/">水种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/longshizhong/">龙石种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/mayazhong/">马牙种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/jinsizhong/">金丝种</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/baidiqingfeicui/">白底青翡翠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/huaqing/">花青</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/lianoufenfeicui/">莲藕粉翡翠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/feicui/chundaicai/">春带彩</a></li>
            					
								</ol>
							</li><li>
								<a target="_blank" href="http://www.zhubao.com/zhenzhu/">珍珠</a>
								<ol>
          						
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/baidiebei/">白蝶贝</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/Akoya/">Akoya</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/daxidiheizhenzhu/">大溪地黑珍珠</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/danshui/">淡水</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/haishui/">海水</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/mashibei/">马氏贝</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/qiebei/">企鹅贝</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/zhenzhu/nanyang/">南洋</a></li>
            					
								</ol>
							</li><li>
								<a target="_blank" href="http://www.zhubao.com/hupo/">琥珀</a>
								<ol>
          						
									<li><a target="_blank" href="http://www.zhubao.com/hupo/baimi/">白蜜</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/hupo/jinpo/">金珀</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/hupo/jinjiaomi/">金绞蜜</a></li>
            					
									<li><a target="_blank" href="http://www.zhubao.com/hupo/mila/">蜜蜡</a></li>
            					
								</ol>
							</li>