<div class="collect_item on_top">
							<span class="img">
								<img src="[field:picname/]">
								<a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="pos_img">
									<img src="{dede:global.cfg_basehost/}/style/images/collect_icon.png">
								</a>
							</span>
							<a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="name">[field:title/]</a>
						</div>