<?php
$z[0]=Array("field","",39,60);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",62,91);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n\r\n									<li><a target=\"_blank\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",121,359);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a> </li>";

?>