-->
			{dede:arclist row='8' titlelen='100' typeid='1,2,3,4'   imgwidth='288' imgheight='288'  flag ='c' orderby ='pubdate'}
				<div class="pro_item on_top">
					<a href="[field:arcurl/]"  target="_blank" class="img">
						<img src="[field:picname/]" alt="[field:title/]">
					</a>
					<a href="[field:arcurl/]" target="_blank" title="[field:title/]" class="txt">[field:title/]</a>
				</div>
			{/dede:arclist}
			<!--