<div class="more">
					<a href="[field:arcurl/]" target="_blank" class="more_top on_top">
						<img src="[field:picname/]">
						<span class="big">[field:typename/]</span>
						<span class="small">[field:title/]</span>
					</a>
					<a href="[field:typeurl/]" target="_blank" class="more_bottom on_top">
						<span class="big">浏览更多</span>
						<span class="small">新品推荐</span>
						<img src="/style/images/new_pro_more_icon.png">
					</a>
				</div>