<?php
$z[0]=Array("id","\" title=\"[field:title",186,219);
$z[1]=Array("picname","",276,292);
$z[2]=Array("title","",320,334);
$z[3]=Array("id","\" title=\"[field:title",457,490);
$z[4]=Array("title","",517,531);
$z[5]=Array("description","",581,631);
$z[5][4]['function']="cn_substr(@me,400)";
$z[6]=Array("pubdate","",680,725);
$z[6][4]['function']="MyDate('m-d',@me)";
$z[7]=Array("click","",883,897);

?>