<li>
										<a href="view.php?aid=[field:id/]" target="_blank" class="img" title="[field:title/]">
											<img src="[field:litpic/]" class="cover-image" style='height:200px;' alt="[field:title/]">
										</a>
										<a href="view.php?aid=[field:id/]" target="_blank" class="txt" title="[field:title/]">[field:title/]</a>
										<p class='margin-bottom-0 red-600'>[field:jiage/]元</p>
									</li>