<?php
$z[0]=Array("id","\" title=\"[field:title",187,220);
$z[1]=Array("picname","",277,293);
$z[2]=Array("title","",321,335);
$z[3]=Array("id","\" title=\"[field:title",459,492);
$z[4]=Array("title","",519,533);
$z[5]=Array("description","",583,633);
$z[5][4]['function']="cn_substr(@me,400)";
$z[6]=Array("pubdate","",682,727);
$z[6][4]['function']="MyDate('m-d',@me)";
$z[7]=Array("click","",885,899);

?>