<li>
					<a  class="pro_img" href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" title="[field:description function="cn_substr(@me,500)"/]"></a>
					<div class="txt">
						<h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3>
						<p title="[field:description function="cn_substr(@me,200)"/]">[field:description function="cn_substr(@me,500)"/]... </p>
						<span>[field:jiage/]元</span>
					</div>
				</li>