<?php
$z[0]=Array("arcurl","",37,52);
$z[1]=Array("picname","",80,96);
$z[2]=Array("description","",105,155);
$z[2][4]['function']="cn_substr(@me,500)";
$z[3]=Array("arcurl","",206,221);
$z[4]=Array("title","",230,244);
$z[5]=Array("title","",262,276);
$z[6]=Array("description","",303,353);
$z[6][4]['function']="cn_substr(@me,200)";
$z[7]=Array("description","",355,405);
$z[7][4]['function']="cn_substr(@me,500)";
$z[8]=Array("jiage","",427,441);

?>