<li>
								<div class="pic">
									<img style="width: 260px;height:160px;" src="[field:litpic/]"/>
									<a target="_blank" href="[field:id runphp='yes'] $id=@me;@me=”;$url=GetOneArchive($id);@me=$url['arcurl'];[/field:id]"><img src="/style/images/ad05.png"/></a>
								</div>
								<h2><a target="_blank" href="[field:id runphp='yes'] $id=@me;@me=”;$url=GetOneArchive($id);@me=$url['arcurl'];[/field:id]">[field:title/]</a></h2>								
							</li>