<?php
$z[0]=Array("id","\" title=\"[field:title",114,147);
$z[1]=Array("picname","",206,222);
$z[2]=Array("title","",251,265);
$z[3]=Array("id","\" title=\"[field:title",398,431);
$z[4]=Array("title","",460,474);
$z[5]=Array("description","",529,578);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",629,676);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("writer","",700,715);
$z[8]=Array("click","",800,814);

?>