<li data-type="list_116">
					<div class="widget widget-shadow invisible" data-plugin="appear" data-animate="slide-bottom50" data-repeat="false">
						<figure class="widget-header cover">
							<a href="list.php?aid=[field:id/]" title="[field:title/]" target='_self'>
								<img class="cover-image" src="[field:picname/]" style='height:300px;' alt="[field:title/]">
							</a>
						</figure>
						<h4 class="widget-title">
							<a href="list.php?aid=[field:id/]" title="[field:title/]" target='_self'>[field:title/]</a>
							<p class='margin-bottom-0 margin-top-5 red-600'>[field:jiage/]元</p>
						</h4>
					</div>