<li class="shown">
					<div class="widget widget-shadow">
						<figure class="widget-header cover">
							<a href="prodetails.html" title="Apple Watch Sport" target='_self'>
								<img class="cover-image" src="{dede:global.cfg_basehost/}{dede:global.cfg_templets_skin/}/img/pro01.jpg" alt="Apple Watch Sport" style='height:200px;'>
							</a>
						</figure>
						<h4 class="widget-title">
							<a href="showproduct.php?lang=cn&id=48" title="Apple Watch Sport" target='_self'>Apple Watch Sport</a>
							<p class='margin-bottom-0 margin-top-5 red-600'>2288.00元</p>
						</h4>
					</div>
				</li>