<li class="clear">
									<a target="_blank" href="[field:arcurl/]"><img src="[field:picname/]"/></a>
									<div class="details">
										<h2><a target="_blank" href="[field:arcurl/]">[field:title/]</a></h2>
										<p>[field:description function="cn_substr(@me,400)"/]... </p>
										<span>
											<span>作者：[field:writer/]</span>
											<span>发表时间：[field:pubdate function="GetDateTimeMK(@me)" /]</span>
											<span>浏览量： [field:click/] </span>
										</span>
									</div>
								</li>