<li class="shown">
					<div class="widget widget-shadow">
						<figure class="widget-header cover">
							<a href="prodetails.html" title="[field:title/]" target='_self'>
								<img class="cover-image" src="[field:picname/]" alt="[field:title/]" style='height:200px;'>
							</a>
						</figure>
						<h4 class="widget-title">
							<a href="view.php?aid=[field:id]" title="[field:title/]" target='_self'>[field:title/]</a>
							<p class='margin-bottom-0 margin-top-5 red-600'>[field:jiage/]元</p>
						</h4>
					</div>
				</li>