<?php
$z[0]=Array("title","",126,140);
$z[1]=Array("picname","",199,215);
$z[2]=Array("title","",244,258);
$z[3]=Array("title","",403,417);
$z[4]=Array("title","",446,460);
$z[5]=Array("description","",515,565);
$z[5][4]['function']="cn_substr(@me,500)";
$z[6]=Array("pubdate","",616,663);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("writer","",687,702);
$z[8]=Array("click","",787,801);

?>