<li>
										<a href="prodetails.html" target="_blank" class="img" title="{dede:field.title/}">
											<img src="{dede:global.cfg_templets_skin/}/img/pro01.jpg" class="cover-image" style='height:200px;' alt="{dede:field.title/}">
										</a>
										<a href="prodetails.html" target="_blank" class="txt" title="{dede:field.title/}">{dede:field.title/}</a>
										<p class='margin-bottom-0 red-600'>2288.00元</p>
									</li>