<?php
$z[0]=Array("channelartlist"," \r\n			<div class=\"col-md-2 col-sm-3 col-xs-6 list masonry-item\">\r\n				<h4><a href=\"list.php?tid={dede:field name='id'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h4>\r\n				<ul>\r\n{dede:channel type='son' row=''}\r\n					<li><a href=\"list.php?tid=[field:id/]\"  title=\"[field:typename/]\">[field:typename/]</a></li>\r\n{/dede:channel}\r\n\r\n				</ul>\r\n			</div>\r\n\r\n",101,549);
$z[0][4]['row']="";
$z[0][4]['typeid']="id";
$z[1]=Array("global","",637,659);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",668,690);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",692,714);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",980,1006);
$z[4][4]['name']="cfg_erweima";
$z[5]=Array("global","",1115,1136);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",1418,1444);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1445,1469);
$z[7][4]['name']="cfg_beian";
$z[8]=Array("global","",1663,1695);
$z[8][4]['name']="cfg_templets_skin";

?>