<?php
$z[0]=Array("global","",822,848);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",874,900);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",957,984);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",984,1007);
$z[3][4]['name']="cfg_logo";
$z[4]=Array("global","",1014,1040);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1049,1075);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1711,1739);
$z[6][4]['name']="cfg_indexname";
$z[7]=Array("global","",1761,1789);
$z[7][4]['name']="cfg_indexname";
$z[8]=Array("channelartlist"," \r\n					<li class=\"margin-left-40\">\r\n						<a\r\n							class=\"dropdown-toggle link \"\r\n							data-toggle=\"dropdown\"\r\n							data-hover=\"dropdown\"\r\n							href=\"list.php?tid={dede:field name='id'/}\"\r\n							aria-expanded=\"false\"\r\n							title=\"{dede:field name='typename'/}\"\r\n						>{dede:field name='typename'/} <span class=\"caret\"></span></a>\r\n						<ul class=\"dropdown-menu dropdown-menu-right animate\">\r\n							{dede:channel type='son' row=''}\r\n							<li><a href=\"list.php?tid=[field:id/]\" class=\"\"  title=\"[field:typename/]\">[field:typename/]</a></li>\r\n							{/dede:channel}\r\n						</ul>\r\n					</li>\r\n",1800,2469);
$z[8][4]['row']="4";
$z[8][4]['typeid']="id";
$z[9]=Array("channelartlist","\r\n<li><a href=\"list.php?tid={dede:field name='id'/}\" class=\"\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></li>\r\n",2471,2690);
$z[9][4]['row']="5";
$z[9][4]['typeid']="43,46,44,45,47,48";

?>