<?php
$z[0]=Array("field","",40,63);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",457,486);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",523,582);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",614,646);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",697,736);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("include","",4031,4070);
$z[5][4]['filename']="footer_m.htm";

?>