<?php
$z[0]=Array("field","",43,66);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",109,138);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",178,237);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",298,325);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",383,410);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",477,504);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",585,612);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("include","",679,716);
$z[7][4]['filename']="header.htm";
$z[8]=Array("global","",800,827);
$z[8][4]['name']="cfg_basehost";
$z[9]=Array("field","",964,993);
$z[9][4]['name']="position";
$z[10]=Array("arclist","\r\n								<li><a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n							",1127,1299);
$z[10][4]['row']="10";
$z[10][4]['titlelen']="40";
$z[10][4]['typeid']="43";
$z[10][4]['orderby']="pubdate";
$z[11]=Array("list","\r\n								<li class=\"clear\">\r\n									<a target=\"_blank\" href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"/></a>\r\n									<div class=\"details\">\r\n										<h2><a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n										<p>[field:description function=\"cn_substr(@me,400)\"/]... </p>\r\n										<span>\r\n											<span>作者：[field:writer/]</span>\r\n											<span>发表时间：[field:pubdate function=\"GetDateTimeMK(@me)\" /]</span>\r\n											<span>浏览量： [field:click/] </span>\r\n										</span>\r\n									</div>\r\n								</li>\r\n							",1396,2003);
$z[11][4]['pagesize']="6";
$z[12]=Array("pagelist","",2071,2128);
$z[12][4]['listitem']="pre,pageno,next,";
$z[12][4]['listsize']="5";
$z[13]=Array("include","",2257,2294);
$z[13][4]['filename']="footer.htm";

?>