<?php
$z[0]=Array("field","",40,63);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",103,132);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",169,228);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",614,646);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",696,735);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",781,804);
$z[5][4]['name']="id";
$z[6]=Array("field","",941,970);
$z[6][4]['name']="typename";
$z[7]=Array("channel","\n							<li class=\"mycur[field:id/]\"><a class=\"link\" href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\n							",1165,1327);
$z[7][4]['type']="son";
$z[8]=Array("list","\n				<li class=\"shown\">\n					<div class=\"widget widget-shadow\">\n						<figure class=\"widget-header cover\">\n							<a href=\"view.php?aid=[field:id]\" title=\"[field:title/]\" target='_self'>\n								<img class=\"cover-image\" src=\"[field:picname/]\" alt=\"[field:title/]\" style='height:200px;'>\n							</a>\n						</figure>\n						<h4 class=\"widget-title\">\n							<a href=\"view.php?aid=[field:id]\" title=\"[field:title/]\" target='_self'>[field:title/]</a>\n							<p class='margin-bottom-0 margin-top-5 red-600'>[field:jiage/]元</p>\n						</h4>\n					</div>\n				</li>\n\n",1575,2169);
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",2253,2310);
$z[9][4]['listitem']="pre,pageno,next,";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2379,2418);
$z[10][4]['filename']="footer_m.htm";

?>