<?php
$z[0]=Array("global","",438,470);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",520,559);
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("list","\n					<li class=\"list-group-item\">\n						<h4>\n							<a href=\"/m/view.php?aid=[field:id/]\">\n							[field:title/]\n							</a>\n						</h4>\n						</a>\n						<p>[field:description/]...</p>\n					</li>\n",1511,1743);
$z[2][4]['perpage']="1";
$z[3]=Array("pagelist","",1831,1888);
$z[3][4]['listitem']="pre,pageno,next,";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",1986,2025);
$z[4][4]['filename']="footer_m.htm";

?>